const express = require('express');
const router = express.Router();
const concertsController = require('../controllers/concerts.controller');
router.get('/concerts', concertsController.getAll);
router.get('concerts/:id', concertsController.getId);
router.post('/concerts', concertsController.postOne);
router.put('concerts/:id', concertsController.putId);
router.delete('concerts/:id', concertsController.deleteId);
router.get('/concerts/performer/:performer', concertsController.getPerformer);
router.get('/concerts/genre/:genre', concertsController.getGenre);
router.get('/concerts/price/:price_min/:price_max', concertsController.getPrice);
router.get('/concerts/day/:day', concertsController.getDay);
module.exports = router;