const express = require('express');
const router = express.Router();
const testimonialsController = require('../controllers/testimonials.controller');
router.get('/testimonials', testimonialsController.getAll);
router.get('testimonials/random', testimonialsController.getRandom);
router.get('testimonials/:id', testimonialsController.getId);
router.post('/testimonials', testimonialsController.postOne);
router.put('testimonials/:id', testimonialsController.putId);
router.delete('testimonials/:id', testimonialsController.deleteId);
module.exports = router;